#!/bin/bash
# Seal-headed deep-sea diver through the lane that produced the working assets.
#
# Same shape as run_moss_titan.sh, with one stage added: the billboard gate
# after geometry. The greentree came back from TRELLIS as two crossed cardboard
# panels with `success: true` and a finalizer note listing every stage, and the
# only thing that caught it was rendering it and looking. That check is now a
# number, and it runs before the forty-minute paint rather than after.
#
# Do not edit this file while it is running. A shell reads a script by byte
# offset, so an edit mid-run resumes at the wrong offset in the new bytes;
# run_moss_titan.sh produced `line 44: ceipt: command not found` that way.
set -e
cd "$(dirname "$0")/.."

PY="C:/Users/Lauri/AppData/Local/LowVRAM3DStudio/envs/control/Scripts/python.exe"
HY="C:/AI/HY3D2/python_standalone/python.exe"
D=evidence/compare/sealdiver
VIEWS="profile,three_quarter,end_plus,three_quarter_rear,profile_far,three_quarter_far,end_minus,plan,below"

LIVE=$D/run_live.log
: > "$LIVE"

stage() {
    printf '\n[%s] === %s\n' "$(date +%H:%M:%S)" "$1" | tee -a "$LIVE"
}

run() {      # streamed as it goes; tail is only the terminal summary
    "$@" 2>&1 | tee -a "$LIVE" | tail -4
    return "${PIPESTATUS[0]}"
}

render() {   # mesh, prefix -- clay AND native, nine views, 2000 px
    [ -s "$1" ] || return 0
    for mode in native clay; do
        "$PY" workers/render_asset_views.py --mesh "$1" --out "${2}_${mode}.png" \
            --views "$VIEWS" --size 2000 --$mode >/dev/null 2>&1 || continue
        "$PY" workers/reflow_view_sheet.py --sheet "${2}_${mode}.png" \
            --views 9 --columns 3 >/dev/null 2>&1 || true
        echo "    rendered ${2}_${mode}_grid.png" | tee -a "$LIVE"
    done
}

stage "conditioning 1024 (geometry) and 512 (paint)"
run "$PY" workers/prepare_input.py --image $D/matte.png \
    --out $D/sealdiver_input_1024.png --res 1024 \
    --receipt $D/sealdiver_input_1024.json
run "$PY" workers/prepare_input.py --image $D/matte.png \
    --out $D/sealdiver_input_512.png --res 512 \
    --receipt $D/sealdiver_input_512.json

stage "TRELLIS 1024 seed 12345"
run "$PY" workers/trellis_run.py --image $D/sealdiver_input_1024.png \
    --out $D/sealdiver_t1024.glb --res 1024 --seed 12345 --tex-res 512 \
    --receipt $D/sealdiver_t1024.json --log $D/sealdiver_t1024.log

stage "billboard gate"
run "$PY" tools/check_not_billboard.py --mesh $D/sealdiver_t1024.glb \
    --receipt $D/sealdiver_t1024.billboard.json

stage "geometry views"
render $D/sealdiver_t1024.glb $D/views_sealdiver_t1024

# 512 conditioning for paint even though geometry used 1024: the paint pipeline
# runs float16 and cuBLAS picks a GEMM per tensor shape, and shapes from a large
# conditioning image land on a tensor-core path TU116 does not have. See f5459a5.
stage "vendor paint 2048 (512 conditioning)"
PYTHONPATH="C:/AI/HY3D2/Hunyuan3D-2" run "$HY" workers/hunyuan_paint_texture.py \
    --mesh $D/sealdiver_t1024.glb --image $D/sealdiver_input_512.png \
    --out $D/sealdiver_t1024_paint2048.glb \
    --render-size 1024 --texture-size 2048 \
    --receipt $D/sealdiver_t1024_paint2048.paint.json

stage "painted views"
render $D/sealdiver_t1024_paint2048.glb $D/views_sealdiver_paint2048

stage "############ SEAL DIVER DONE"
ls -la $D/*_grid.png 2>/dev/null | awk '{print "  ", $NF, $5}'
